"""gds-software — DEPRECATED: use gds_domains.software instead."""

import warnings

warnings.warn(
    "Import from gds_domains.software instead of gds_software. "
    "The gds-software package will be removed in v0.3.0.",
    DeprecationWarning,
    stacklevel=2,
)

__version__ = "0.99.0"

from gds_domains.software import (  # noqa: F401, E402
    ALL_C4_CHECKS,
    ALL_CP_CHECKS,
    ALL_DFD_CHECKS,
    ALL_DG_CHECKS,
    ALL_ER_CHECKS,
    ALL_SM_CHECKS,
    Attribute,
    C4Component,
    C4Model,
    C4Relationship,
    Cardinality,
    Component,
    ComponentModel,
    Connector,
    Container,
    ContentSpace,
    ContentType,
    DataFlow,
    DataSpace,
    DataStore,
    DataType,
    DFDModel,
    Dep,
    DependencyModel,
    DiagramKind,
    ERDEntity,
    ERDModel,
    ERDRelationship,
    Event,
    EventSpace,
    EventType,
    ExternalEntity,
    ExternalSystem,
    Finding,
    Guard,
    InterfaceDef,
    Layer,
    Module,
    Person,
    Process,
    Region,
    SWCompilationError,
    SWError,
    SWValidationError,
    Severity,
    SignalSpace,
    SignalType,
    State,
    StateMachineModel,
    StateSpace,
    StateType,
    Transition,
    VerificationReport,
    check_c4001_relationship_validity,
    check_c4002_container_hierarchy,
    check_c4003_external_connectivity,
    check_c4004_level_consistency,
    check_cp001_interface_satisfaction,
    check_cp002_connector_validity,
    check_cp003_dangling_interfaces,
    check_cp004_component_naming,
    check_dfd001_process_connectivity,
    check_dfd002_flow_validity,
    check_dfd003_no_ext_to_ext,
    check_dfd004_store_connectivity,
    check_dfd005_process_output,
    check_dg001_dep_validity,
    check_dg002_acyclicity,
    check_dg003_layer_ordering,
    check_dg004_module_connectivity,
    check_er001_relationship_validity,
    check_er002_pk_existence,
    check_er003_attribute_uniqueness,
    check_er004_relationship_naming,
    check_sm001_initial_state,
    check_sm002_reachability,
    check_sm003_determinism,
    check_sm004_guard_completeness,
    check_sm005_region_partition,
    check_sm006_transition_validity,
    compile_c4,
    compile_c4_to_system,
    compile_component,
    compile_component_to_system,
    compile_dep,
    compile_dep_to_system,
    compile_dfd,
    compile_dfd_to_system,
    compile_erd,
    compile_erd_to_system,
    compile_sm,
    compile_sm_to_system,
    verify,
)

__all__ = [
    # Common
    "DiagramKind",
    "SWError",
    "SWValidationError",
    "SWCompilationError",
    # DFD
    "ExternalEntity",
    "Process",
    "DataStore",
    "DataFlow",
    "DFDModel",
    "compile_dfd",
    "compile_dfd_to_system",
    "ContentType",
    "ContentSpace",
    "DataType",
    "DataSpace",
    "SignalType",
    "SignalSpace",
    "ALL_DFD_CHECKS",
    "check_dfd001_process_connectivity",
    "check_dfd002_flow_validity",
    "check_dfd003_no_ext_to_ext",
    "check_dfd004_store_connectivity",
    "check_dfd005_process_output",
    # State Machine
    "State",
    "Event",
    "Transition",
    "Guard",
    "Region",
    "StateMachineModel",
    "compile_sm",
    "compile_sm_to_system",
    "EventType",
    "EventSpace",
    "StateType",
    "StateSpace",
    "ALL_SM_CHECKS",
    "check_sm001_initial_state",
    "check_sm002_reachability",
    "check_sm003_determinism",
    "check_sm004_guard_completeness",
    "check_sm005_region_partition",
    "check_sm006_transition_validity",
    # Component
    "Component",
    "Connector",
    "InterfaceDef",
    "ComponentModel",
    "compile_component",
    "compile_component_to_system",
    "ALL_CP_CHECKS",
    "check_cp001_interface_satisfaction",
    "check_cp002_connector_validity",
    "check_cp003_dangling_interfaces",
    "check_cp004_component_naming",
    # C4
    "Person",
    "ExternalSystem",
    "Container",
    "C4Component",
    "C4Relationship",
    "C4Model",
    "compile_c4",
    "compile_c4_to_system",
    "ALL_C4_CHECKS",
    "check_c4001_relationship_validity",
    "check_c4002_container_hierarchy",
    "check_c4003_external_connectivity",
    "check_c4004_level_consistency",
    # ERD
    "ERDEntity",
    "Attribute",
    "ERDRelationship",
    "Cardinality",
    "ERDModel",
    "compile_erd",
    "compile_erd_to_system",
    "ALL_ER_CHECKS",
    "check_er001_relationship_validity",
    "check_er002_pk_existence",
    "check_er003_attribute_uniqueness",
    "check_er004_relationship_naming",
    # Dependency
    "Module",
    "Dep",
    "Layer",
    "DependencyModel",
    "compile_dep",
    "compile_dep_to_system",
    "ALL_DG_CHECKS",
    "check_dg001_dep_validity",
    "check_dg002_acyclicity",
    "check_dg003_layer_ordering",
    "check_dg004_module_connectivity",
    # Verification
    "verify",
    # Re-exports
    "Finding",
    "Severity",
    "VerificationReport",
]
