"""gds-business — DEPRECATED: use gds_domains.business instead."""

import warnings

warnings.warn(
    "Import from gds_domains.business instead of gds_business. "
    "The gds-business package will be removed in v0.3.0.",
    DeprecationWarning,
    stacklevel=2,
)

__version__ = "0.99.0"

from gds_domains.business import (  # noqa: F401, E402
    ALL_CLD_CHECKS,
    ALL_SCN_CHECKS,
    ALL_VSM_CHECKS,
    BizCompilationError,
    BizError,
    BizValidationError,
    BusinessDiagramKind,
    CausalLink,
    CausalLoopModel,
    Customer,
    DemandSource,
    DemandSpace,
    DemandType,
    Finding,
    InformationFlow,
    InventoryBuffer,
    InventorySpace,
    InventoryType,
    MaterialFlow,
    MaterialSpace,
    MaterialType,
    OrderPolicy,
    ProcessSignalSpace,
    ProcessSignalType,
    ProcessStep,
    Severity,
    Shipment,
    ShipmentRateSpace,
    ShipmentRateType,
    SignalSpace,
    SignalType,
    Supplier,
    SupplyChainModel,
    SupplyNode,
    ValueStreamModel,
    Variable,
    VerificationReport,
    check_cld001_loop_polarity,
    check_cld002_variable_reachability,
    check_cld003_no_self_loops,
    check_scn001_network_connectivity,
    check_scn002_shipment_node_validity,
    check_scn003_demand_target_validity,
    check_scn004_no_orphan_nodes,
    check_vsm001_linear_process_flow,
    check_vsm002_push_pull_boundary,
    check_vsm003_flow_reference_validity,
    check_vsm004_bottleneck_vs_takt,
    compile_cld,
    compile_cld_to_system,
    compile_scn,
    compile_scn_to_system,
    compile_vsm,
    compile_vsm_to_system,
    verify,
)

__all__ = [
    # Common
    "BusinessDiagramKind",
    "BizError",
    "BizValidationError",
    "BizCompilationError",
    # CLD
    "Variable",
    "CausalLink",
    "CausalLoopModel",
    "compile_cld",
    "compile_cld_to_system",
    "SignalType",
    "SignalSpace",
    "ALL_CLD_CHECKS",
    "check_cld001_loop_polarity",
    "check_cld002_variable_reachability",
    "check_cld003_no_self_loops",
    # Supply Chain
    "SupplyNode",
    "Shipment",
    "DemandSource",
    "OrderPolicy",
    "SupplyChainModel",
    "compile_scn",
    "compile_scn_to_system",
    "InventoryType",
    "InventorySpace",
    "ShipmentRateType",
    "ShipmentRateSpace",
    "DemandType",
    "DemandSpace",
    "ALL_SCN_CHECKS",
    "check_scn001_network_connectivity",
    "check_scn002_shipment_node_validity",
    "check_scn003_demand_target_validity",
    "check_scn004_no_orphan_nodes",
    # VSM
    "ProcessStep",
    "InventoryBuffer",
    "Supplier",
    "Customer",
    "MaterialFlow",
    "InformationFlow",
    "ValueStreamModel",
    "compile_vsm",
    "compile_vsm_to_system",
    "MaterialType",
    "MaterialSpace",
    "ProcessSignalType",
    "ProcessSignalSpace",
    "ALL_VSM_CHECKS",
    "check_vsm001_linear_process_flow",
    "check_vsm002_push_pull_boundary",
    "check_vsm003_flow_reference_validity",
    "check_vsm004_bottleneck_vs_takt",
    # Verification
    "verify",
    # Re-exports
    "Finding",
    "Severity",
    "VerificationReport",
]
