"""E-Commerce Order Processing — Data Flow Diagram (DFD).

Models an e-commerce order processing system as a DFD using the
gds-software declarative DSL. External entities (Customer, Payment
Provider) interact with processes (Validate Order, Process Payment,
Fulfill Order) that read/write data stores (Orders DB, Inventory DB).

Concepts Covered:
    - DFDModel declarative API (ExternalEntity, Process, DataStore, DataFlow)
    - compile_dfd() → GDSSpec (automatic type/space/entity/block generation)
    - compile_dfd_to_system() → SystemIR (automatic composition with .loop())
    - verify() — DFD-001..DFD-005 + GDS G-001..G-006
    - Canonical h = f ∘ g decomposition for software architecture

Prerequisites: gds-software package

GDS Decomposition (auto-generated by compiler):
    X  = (Orders DB.content, Inventory DB.content)
    U  = (Customer, Payment Provider)  — external entity signals
    g  = (Validate Order, Process Payment, Fulfill Order)  — process policies
    f  = (Orders DB Store, Inventory DB Store)  — data store mechanisms
    Θ  = {}  — no parameters

Composition (auto-generated):
    (Customer | Payment Provider)
        >> (Validate Order | Process Payment | Fulfill Order)
        >> (Orders DB Store | Inventory DB Store)
    .loop([Orders DB Store → Process Payment,
           Orders DB Store → Fulfill Order,
           Inventory DB Store → Fulfill Order])
"""

from gds.canonical import CanonicalGDS, project_canonical
from gds.ir.models import SystemIR
from gds.spec import GDSSpec
from gds_software.dfd.compile import compile_dfd, compile_dfd_to_system
from gds_software.dfd.elements import DataFlow, DataStore, ExternalEntity, Process
from gds_software.dfd.model import DFDModel


def build_model() -> DFDModel:
    """Declare the e-commerce order processing system as a DFDModel.

    The model captures the *structure* of order processing:
    - Customer submits orders, receives status updates
    - Payment Provider handles payment requests and confirmations
    - Three processes validate, pay, and fulfill orders
    - Two data stores persist order records and inventory state

    The compiler infers all types, spaces, entities, blocks, and wirings
    from these declarations.
    """
    return DFDModel(
        name="Order Processing",
        external_entities=[
            ExternalEntity(
                name="Customer",
                description="End user placing orders",
            ),
            ExternalEntity(
                name="Payment Provider",
                description="External payment gateway",
            ),
        ],
        processes=[
            Process(
                name="Validate Order",
                description="Validates order details and checks inventory",
            ),
            Process(
                name="Process Payment",
                description="Handles payment authorization and capture",
            ),
            Process(
                name="Fulfill Order",
                description="Picks, packs, and ships the order",
            ),
        ],
        data_stores=[
            DataStore(
                name="Orders DB",
                description="Persistent store of order records",
            ),
            DataStore(
                name="Inventory DB",
                description="Persistent store of product inventory levels",
            ),
        ],
        data_flows=[
            # Customer → Validate Order
            DataFlow(
                name="Order Request",
                source="Customer",
                target="Validate Order",
                data="Order details (items, quantities, shipping address)",
            ),
            # Validate Order → Process Payment
            DataFlow(
                name="Payment Request",
                source="Validate Order",
                target="Process Payment",
                data="Validated order total and payment method",
            ),
            # Process Payment → Payment Provider
            DataFlow(
                name="Payment Authorization",
                source="Process Payment",
                target="Payment Provider",
                data="Payment charge request",
            ),
            # Payment Provider → Process Payment
            DataFlow(
                name="Payment Confirmation",
                source="Payment Provider",
                target="Process Payment",
                data="Authorization result (approved/declined)",
            ),
            # Process Payment → Fulfill Order
            DataFlow(
                name="Fulfillment Request",
                source="Process Payment",
                target="Fulfill Order",
                data="Paid order ready for fulfillment",
            ),
            # Fulfill Order → Customer
            DataFlow(
                name="Order Status",
                source="Fulfill Order",
                target="Customer",
                data="Shipping confirmation and tracking info",
            ),
            # Validate Order → Orders DB (write)
            DataFlow(
                name="Order Record",
                source="Validate Order",
                target="Orders DB",
                data="New order record",
            ),
            # Orders DB → Process Payment (read)
            DataFlow(
                name="Order Lookup",
                source="Orders DB",
                target="Process Payment",
                data="Order details for payment processing",
            ),
            # Orders DB → Fulfill Order (read)
            DataFlow(
                name="Order Details",
                source="Orders DB",
                target="Fulfill Order",
                data="Order details for fulfillment",
            ),
            # Fulfill Order → Inventory DB (write)
            DataFlow(
                name="Stock Update",
                source="Fulfill Order",
                target="Inventory DB",
                data="Inventory deduction after shipment",
            ),
            # Inventory DB → Fulfill Order (read)
            DataFlow(
                name="Stock Check",
                source="Inventory DB",
                target="Fulfill Order",
                data="Current inventory levels",
            ),
        ],
        description="E-commerce order processing data flow diagram",
    )


def build_spec() -> GDSSpec:
    """Compile the DFDModel to a full GDSSpec.

    The compiler automatically generates:
    - 3 semantic types: DFD Signal, DFD Data, DFD Content
    - 3 semantic spaces: DFD SignalSpace, DFD DataSpace, DFD ContentSpace
    - 2 entities: Orders DB (content), Inventory DB (content)
    - 7 blocks: 2 BoundaryAction (externals), 3 Policy (processes),
                2 Mechanisms (data store updates)
    - 1 SpecWiring with all inter-element connections
    """
    return compile_dfd(build_model())


def build_system() -> SystemIR:
    """Compile the DFDModel to SystemIR via the composition tree.

    The compiler builds:
        (Customer | Payment Provider)
            >> (Validate Order | Process Payment | Fulfill Order)
            >> (Orders DB Store | Inventory DB Store)
        .loop([
            Orders DB Store -> Process Payment (COVARIANT),
            Orders DB Store -> Fulfill Order (COVARIANT),
            Inventory DB Store -> Fulfill Order (COVARIANT),
        ])

    The .loop() creates temporal recurrence — data store content at
    timestep t feeds process inputs at timestep t+1.
    """
    return compile_dfd_to_system(build_model())


def build_canonical() -> CanonicalGDS:
    """Project the canonical h = f . g decomposition.

    For the order processing DFD:
        |X| = 2  (Orders DB content, Inventory DB content)
        |U| = 2  (Customer, Payment Provider)
        |g| = 3  (Validate Order, Process Payment, Fulfill Order)
        |f| = 2  (Orders DB Store, Inventory DB Store mechanisms)
    """
    return project_canonical(build_spec())
