"""Resource Pool — Stock-Flow View.

Models a shared resource pool (e.g., water reservoir, inventory) as a
stock-flow system. Resource level is a Stock that accumulates via a
supply inflow and depletes via a consumption outflow. An auxiliary
computes the net rate from supply and consumption parameters.

GDS Decomposition (auto-generated by StockFlow compiler):
    X  = resource_level         -- accumulated stock level
    U  = (supply_rate, consumption_rate)  -- exogenous parameters
    g  = (net_rate, supply, consumption)  -- rate computations (Policy)
    f  = (ResourceLevel Accumulation)     -- state update (Mechanism)
    Theta = {supply_rate, consumption_rate}

Composition (auto-generated):
    (supply_rate | consumption_rate) >> net_rate >> (supply | consumption)
        >> ResourceLevel Accumulation
"""

from gds.canonical import CanonicalGDS, project_canonical
from gds.ir.models import SystemIR
from gds.spec import GDSSpec
from stockflow.dsl.compile import compile_model, compile_to_system
from stockflow.dsl.elements import Auxiliary, Converter, Flow, Stock
from stockflow.dsl.model import StockFlowModel


def build_model() -> StockFlowModel:
    """Declare the resource pool as a StockFlowModel.

    Structure:
    - One Stock: ResourceLevel (the pool accumulator)
    - Two Flows: supply (inflow from cloud), consumption (outflow to cloud)
    - One Auxiliary: net_rate (computes net from supply - consumption)
    - Two Converters: supply_rate, consumption_rate (exogenous parameters)
    """
    return StockFlowModel(
        name="Resource Pool (Stock-Flow)",
        stocks=[
            Stock(name="ResourceLevel", initial=100.0, non_negative=True),
        ],
        flows=[
            Flow(name="supply", target="ResourceLevel"),
            Flow(name="consumption", source="ResourceLevel"),
        ],
        auxiliaries=[
            Auxiliary(name="net_rate", inputs=["supply_rate", "consumption_rate"]),
        ],
        converters=[
            Converter(name="supply_rate"),
            Converter(name="consumption_rate"),
        ],
        description=(
            "Shared resource pool with supply inflow and consumption outflow. "
            "Stock-flow perspective on resource management."
        ),
    )


def build_spec() -> GDSSpec:
    """Compile the StockFlowModel to a full GDSSpec."""
    return compile_model(build_model())


def build_system() -> SystemIR:
    """Compile the StockFlowModel to SystemIR via the composition tree."""
    return compile_to_system(build_model())


def build_canonical() -> CanonicalGDS:
    """Project the canonical h = f . g decomposition."""
    return project_canonical(build_spec())
