name: Feature Request
description: Suggest a new feature or enhancement
labels: ["enhancement"]
body:
  - type: dropdown
    id: package
    attributes:
      label: Package
      description: Which package does this relate to?
      options:
        - gds-framework
        - gds-viz
        - gds-games
        - gds-stockflow
        - gds-control
        - gds-examples
        - Other/New
    validations:
      required: true

  - type: textarea
    id: problem-description
    attributes:
      label: Problem description
      description: What problem does this solve?
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed solution
      description: Describe the solution you'd like.
    validations:
      required: true

  - type: textarea
    id: alternatives-considered
    attributes:
      label: Alternatives considered
      description: Describe any alternative solutions or features you've considered.
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Any other context or screenshots about the feature request.
    validations:
      required: false
