"""Gordon-Schaefer Fishery — StockFlow DSL version.

Reimplements the manual fisheries model (fisheries/) using the gds-stockflow
declarative DSL. Instead of manually constructing TypeDefs, Entities, Spaces,
Blocks, and wiring them together, we declare Stocks, Flows, Auxiliaries, and
Converters — the compiler handles all GDS mapping.

Note: The DSL version cannot express ControlAction (quota enforcement) or
.feedback() (within-timestep backward flow). Those require the hand-built
model in fisheries/. This version models a simpler bioeconomic fishery
without regulatory constraints.

Concepts Covered:
    - StockFlowModel declarative API for bioeconomic dynamics
    - compile_model() -> GDSSpec (automatic type/space/entity/block generation)
    - compile_to_system() -> SystemIR (automatic composition with .loop())
    - verify() -- SF-001..SF-005 + GDS G-001..G-006
    - Multi-stock system (fish population + fleet effort)
    - Temporal loops (cross-timestep state feedback)
    - Comparison with manual GDS construction (fisheries/)

Prerequisites: sir_epidemic_dsl (basic stockflow DSL),
               lotka_volterra_dsl (multi-stock temporal loops)

GDS Decomposition (auto-generated by compiler):
    X  = (Fish Stock.level, Fleet Effort.level)
    U  = (Intrinsic Growth Rate, Carrying Capacity, Catchability,
           Market Price, Cost Per Unit Effort, Effort Adjustment Speed)
    g  = (Growth Rate, Harvest Rate, Profit Signal,
           Net Fish Change, Net Effort Change)
    f  = (Fish Stock Accumulation, Fleet Effort Accumulation)
    Theta = {Intrinsic Growth Rate, Carrying Capacity, Catchability,
             Market Price, Cost Per Unit Effort, Effort Adjustment Speed}

Composition (auto-generated):
    (Intrinsic Growth Rate | Carrying Capacity | Catchability
        | Market Price | Cost Per Unit Effort | Effort Adjustment Speed)
    >> (Growth Rate | Harvest Rate | Profit Signal)
    >> (Net Fish Change | Net Effort Change)
    >> (Fish Stock Accumulation | Fleet Effort Accumulation)
    .loop([Fish Stock Accumulation -> Growth Rate,
           Fish Stock Accumulation -> Harvest Rate,
           Fish Stock Accumulation -> Profit Signal,
           Fleet Effort Accumulation -> Harvest Rate,
           Fleet Effort Accumulation -> Profit Signal])

Note vs. hand-built model: the DSL version folds effort_adjustment_speed
into the Profit Signal auxiliary rather than having it as a Mechanism
parameter, since StockFlowModel auxiliaries are the natural place for
rate computations. The hand-built model keeps it on Update Fleet.
"""

from gds.canonical import CanonicalGDS, project_canonical
from gds.ir.models import SystemIR
from gds.spec import GDSSpec
from stockflow.dsl.compile import compile_model, compile_to_system
from stockflow.dsl.elements import Auxiliary, Converter, Flow, Stock
from stockflow.dsl.model import StockFlowModel


def build_model() -> StockFlowModel:
    """Declare the Gordon-Schaefer fishery as a StockFlowModel.

    The model captures the *structure* of a bioeconomic fishery:
    two stocks (fish population, fleet effort) connected by flows that
    represent net population change and net effort change.

    The Gordon-Schaefer equations are:
        dN/dt = r*N*(1 - N/K) - q*E*N     (fish growth minus harvest)
        dE/dt = s*(p*q*E*N - c*E)          (effort responds to profit)

    We decompose these into three rate auxiliaries:
        - Growth Rate:    r * N * (1 - N/K)
        - Harvest Rate:   q * E * N
        - Profit Signal:  p*q*E*N - c*E (revenue minus cost)

    Two net-change flows aggregate into stock-level changes:
        - Net Fish Change:    Growth Rate - Harvest Rate
        - Net Effort Change:  s * Profit Signal

    Six converters provide exogenous parameters: r, K, q, p, c, s.
    """
    return StockFlowModel(
        name="Fisheries Bioeconomic",
        stocks=[
            Stock(name="Fish Stock", initial=1000.0),
            Stock(name="Fleet Effort", initial=50.0),
        ],
        flows=[
            Flow(name="Net Fish Change", target="Fish Stock"),
            Flow(name="Net Effort Change", target="Fleet Effort"),
        ],
        auxiliaries=[
            # Growth: r * N * (1 - N/K)
            Auxiliary(
                name="Growth Rate",
                inputs=["Fish Stock", "Intrinsic Growth Rate", "Carrying Capacity"],
            ),
            # Harvest: q * E * N (Schaefer production function)
            Auxiliary(
                name="Harvest Rate",
                inputs=["Fish Stock", "Fleet Effort", "Catchability"],
            ),
            # Profit: s*(p*q*E*N - c*E) — scaled by effort adjustment speed
            Auxiliary(
                name="Profit Signal",
                inputs=[
                    "Fish Stock",
                    "Fleet Effort",
                    "Market Price",
                    "Cost Per Unit Effort",
                    "Catchability",
                    "Effort Adjustment Speed",
                ],
            ),
        ],
        converters=[
            Converter(name="Intrinsic Growth Rate"),
            Converter(name="Carrying Capacity"),
            Converter(name="Catchability"),
            Converter(name="Market Price"),
            Converter(name="Cost Per Unit Effort"),
            Converter(name="Effort Adjustment Speed"),
        ],
        description="Gordon-Schaefer bioeconomic fishery model",
    )


def build_spec() -> GDSSpec:
    """Compile the StockFlowModel to a full GDSSpec.

    The compiler automatically generates:
    - 4 semantic types: Level, UnconstrainedLevel, Rate, Signal
    - 4 semantic spaces: LevelSpace, UnconstrainedLevelSpace, RateSpace,
      SignalSpace
    - 2 entities: Fish Stock (level), Fleet Effort (level)
    - 13 blocks: 6 BoundaryAction (converters), 3 Policy-auxiliaries,
                 2 Policy-flows, 2 Mechanisms (stock accumulations)
    - 1 SpecWiring with all inter-block connections
    - 6 parameters: one per converter
    """
    return compile_model(build_model())


def build_system() -> SystemIR:
    """Compile the StockFlowModel to SystemIR via the composition tree.

    The compiler builds:
        (Intrinsic Growth Rate | Carrying Capacity | Catchability
            | Market Price | Cost Per Unit Effort | Effort Adjustment Speed)
        >> (Growth Rate | Harvest Rate | Profit Signal)
        >> (Net Fish Change | Net Effort Change)
        >> (Fish Stock Accumulation | Fleet Effort Accumulation)
        .loop([
            Fish Stock Accumulation -> Growth Rate (COVARIANT),
            Fish Stock Accumulation -> Harvest Rate (COVARIANT),
            Fish Stock Accumulation -> Profit Signal (COVARIANT),
            Fleet Effort Accumulation -> Harvest Rate (COVARIANT),
            Fleet Effort Accumulation -> Profit Signal (COVARIANT),
        ])
    """
    return compile_to_system(build_model())


def build_canonical() -> CanonicalGDS:
    """Project the canonical h = f . g decomposition.

    For the fisheries system:
        |X| = 2  (Fish Stock, Fleet Effort levels)
        |U| = 6  (six converter parameters)
        |g| = 5  (3 auxiliaries + 2 flows)
        |f| = 2  (2 stock accumulation mechanisms)
    """
    return project_canonical(build_spec())
