"""gds-psuu — DEPRECATED: use gds_analysis.psuu instead."""

import warnings

warnings.warn(
    "Import from gds_analysis.psuu instead of gds_psuu. "
    "The gds-psuu package will be removed in v0.3.0.",
    DeprecationWarning,
    stacklevel=2,
)

__version__ = "0.99.0"

from gds_analysis.psuu import (  # noqa: F401, E402
    KPI,
    Aggregation,
    AggregationFn,
    Analyzer,
    BayesianOptimizer,
    Constraint,
    Continuous,
    Discrete,
    EvaluationResult,
    EvaluationSummary,
    Evaluator,
    FunctionalConstraint,
    GridSearchOptimizer,
    Integer,
    KPIFn,
    KPIScores,
    LinearConstraint,
    Metric,
    MetricFn,
    MorrisAnalyzer,
    OATAnalyzer,
    Objective,
    Optimizer,
    ParamPoint,
    ParameterSpace,
    PsuuError,
    PsuuSearchError,
    PsuuValidationError,
    RandomSearchOptimizer,
    SchemaViolation,
    SensitivityResult,
    SingleKPI,
    Sweep,
    SweepResults,
    WeightedSum,
    check_parameter_space_compatibility,
    final_state_mean,
    final_state_std,
    final_value,
    max_value,
    mean_agg,
    min_value,
    percentile_agg,
    probability_above,
    probability_below,
    std_agg,
    time_average,
    trajectory_mean,
)

__all__ = [
    "KPI",
    "Aggregation",
    "AggregationFn",
    "Analyzer",
    "BayesianOptimizer",
    "Constraint",
    "Continuous",
    "Discrete",
    "EvaluationResult",
    "EvaluationSummary",
    "Evaluator",
    "FunctionalConstraint",
    "GridSearchOptimizer",
    "Integer",
    "KPIFn",
    "KPIScores",
    "LinearConstraint",
    "Metric",
    "MetricFn",
    "MorrisAnalyzer",
    "OATAnalyzer",
    "Objective",
    "Optimizer",
    "ParamPoint",
    "ParameterSpace",
    "PsuuError",
    "PsuuSearchError",
    "PsuuValidationError",
    "RandomSearchOptimizer",
    "SchemaViolation",
    "SensitivityResult",
    "SingleKPI",
    "Sweep",
    "SweepResults",
    "WeightedSum",
    "check_parameter_space_compatibility",
    "final_state_mean",
    "final_state_std",
    "final_value",
    "max_value",
    "mean_agg",
    "min_value",
    "percentile_agg",
    "probability_above",
    "probability_below",
    "std_agg",
    "time_average",
    "trajectory_mean",
]
