"""SIR Epidemic Model — StockFlow DSL version.

Reimplements the manual SIR epidemic model (sir_epidemic/) using the
gds-stockflow declarative DSL. Instead of manually constructing TypeDefs,
Entities, Spaces, Blocks, and wiring them together, we declare Stocks,
Flows, Auxiliaries, and Converters — the compiler handles all GDS mapping.

Concepts Covered:
    - StockFlowModel declarative API (Stock, Flow, Auxiliary, Converter)
    - compile_model() → GDSSpec (automatic type/space/entity/block generation)
    - compile_to_system() → SystemIR (automatic composition with .loop())
    - verify() — SF-001..SF-005 + GDS G-001..G-006
    - Comparison with manual GDS construction (sir_epidemic/)

Prerequisites: sir_epidemic (manual GDS), gds-stockflow package

GDS Decomposition (auto-generated by compiler):
    X  = (Susceptible.level, Infected.level, Recovered.level)
    U  = (Contact Rate, Recovery Time)  — exogenous converters
    g  = (Infection Rate, Recovery Rate, Infection, Recovery)  — aux + flow policies
    f  = (Susceptible Accumulation, Infected Accumulation, Recovered Accumulation)
    Θ  = {Contact Rate, Recovery Time}  — converters as parameters

Composition (auto-generated):
    (Contact Rate | Recovery Time) >> (Infection Rate | Recovery Rate)
        >> (Infection | Recovery) >> (S Accum | I Accum | R Accum)
    .loop([S Level → Infection Rate, I Level → Infection Rate,
           I Level → Recovery Rate])
"""

from gds.canonical import CanonicalGDS, project_canonical
from gds.ir.models import SystemIR
from gds.spec import GDSSpec
from stockflow.dsl.compile import compile_model, compile_to_system
from stockflow.dsl.elements import Auxiliary, Converter, Flow, Stock
from stockflow.dsl.model import StockFlowModel


def build_model() -> StockFlowModel:
    """Declare the SIR epidemic as a StockFlowModel.

    The model captures the *structure* of the SIR compartmental model:
    three population stocks (S, I, R) connected by two inter-stock flows
    (Infection drains S into I, Recovery drains I into R).

    Two auxiliaries compute the infection and recovery rates from stock
    levels and exogenous parameters. Two converters provide the exogenous
    parameters (Contact Rate, Recovery Time).

    No numerical values are specified — GDS is structural, not numerical.
    The compiler infers all types, spaces, entities, blocks, and wirings
    from these declarations.
    """
    return StockFlowModel(
        name="SIR Epidemic",
        stocks=[
            Stock(name="Susceptible", initial=999.0),
            Stock(name="Infected", initial=1.0),
            Stock(name="Recovered", initial=0.0),
        ],
        flows=[
            Flow(name="Infection", source="Susceptible", target="Infected"),
            Flow(name="Recovery", source="Infected", target="Recovered"),
        ],
        auxiliaries=[
            Auxiliary(
                name="Infection Rate",
                inputs=["Susceptible", "Infected", "Contact Rate"],
            ),
            Auxiliary(
                name="Recovery Rate",
                inputs=["Infected", "Recovery Time"],
            ),
        ],
        converters=[
            Converter(name="Contact Rate"),
            Converter(name="Recovery Time"),
        ],
        description="Susceptible-Infected-Recovered compartmental model",
    )


def build_spec() -> GDSSpec:
    """Compile the StockFlowModel to a full GDSSpec.

    The compiler automatically generates:
    - 4 semantic types: Level, UnconstrainedLevel, Rate, Signal
    - 4 semantic spaces: LevelSpace, UnconstrainedLevelSpace, RateSpace, SignalSpace
    - 3 entities: Susceptible (level), Infected (level), Recovered (level)
    - 9 blocks: 2 BoundaryAction (converters), 2 Policy-auxiliaries,
                2 Policy-flows, 3 Mechanisms (stock accumulations)
    - 1 SpecWiring with all inter-block connections
    - 2 parameters: Contact Rate, Recovery Time
    """
    return compile_model(build_model())


def build_system() -> SystemIR:
    """Compile the StockFlowModel to SystemIR via the composition tree.

    The compiler builds:
        (Contact Rate | Recovery Time) >> (Infection Rate | Recovery Rate)
            >> (Infection | Recovery)
            >> (Susceptible Accumulation | Infected Accumulation
                | Recovered Accumulation)
        .loop([
            Susceptible Accumulation -> Infection Rate (COVARIANT),
            Infected Accumulation -> Infection Rate (COVARIANT),
            Infected Accumulation -> Recovery Rate (COVARIANT),
        ])

    The .loop() creates temporal recurrence -- stock levels at timestep t
    feed auxiliary computations at timestep t+1.
    """
    return compile_to_system(build_model())


def build_canonical() -> CanonicalGDS:
    """Project the canonical h = f . g decomposition.

    For the SIR epidemic:
        |X| = 3  (Susceptible, Infected, Recovered levels)
        |U| = 2  (Contact Rate, Recovery Time)
        |g| = 4  (2 auxiliaries + 2 flows)
        |f| = 3  (3 stock accumulation mechanisms)
    """
    return project_canonical(build_spec())
