"""Resource Pool — Control View.

Models the same resource pool as a feedback control system. The resource
level is a plant state, a target reference level is an exogenous input,
and a controller adjusts the supply rate to track the target.

This is the classical regulation problem:
    x_dot = f(x, u)    ->    x_{t+1} = f(x_t, u_t)    (GDS mechanism)
    y     = g(x)        ->    y_t = g(x_t)               (GDS policy -- sensor)
    u     = K(y, r)     ->    u_t = g(y_t, r_t)          (GDS policy -- controller)

GDS Decomposition (auto-generated by Control compiler):
    X  = resource_level           -- plant state
    U  = target_level             -- exogenous reference setpoint
    g  = (level_sensor, supply_controller)  -- observation + control law
    f  = (resource_level Dynamics)          -- state transition
    Theta = {target_level}

Composition (auto-generated):
    (target_level | level_sensor) >> supply_controller
        >> resource_level Dynamics
        .loop([resource_level Dynamics -> level_sensor])
"""

from gds.canonical import CanonicalGDS, project_canonical
from gds.ir.models import SystemIR
from gds.spec import GDSSpec
from gds_control.dsl.compile import compile_model, compile_to_system
from gds_control.dsl.elements import Controller, Input, Sensor, State
from gds_control.dsl.model import ControlModel


def build_model() -> ControlModel:
    """Declare the resource pool as a ControlModel.

    Structure:
    - One State: resource_level (the controlled plant state)
    - One Input: target_level (exogenous reference setpoint)
    - One Sensor: level_sensor (observes resource_level)
    - One Controller: supply_controller (reads sensor + reference, drives state)
    """
    return ControlModel(
        name="Resource Pool (Control)",
        states=[
            State(name="resource_level", initial=100.0),
        ],
        inputs=[
            Input(name="target_level"),
        ],
        sensors=[
            Sensor(name="level_sensor", observes=["resource_level"]),
        ],
        controllers=[
            Controller(
                name="supply_controller",
                reads=["level_sensor", "target_level"],
                drives=["resource_level"],
            ),
        ],
        description=(
            "Resource pool as a feedback control system. "
            "Controller adjusts supply to track a target reference level."
        ),
    )


def build_spec() -> GDSSpec:
    """Compile the ControlModel to a full GDSSpec."""
    return compile_model(build_model())


def build_system() -> SystemIR:
    """Compile the ControlModel to SystemIR via the composition tree."""
    return compile_to_system(build_model())


def build_canonical() -> CanonicalGDS:
    """Project the canonical h = f . g decomposition."""
    return project_canonical(build_spec())
